name: Daily Commit Workflow

on:
  push:
    branches:
      - main  # Change to "master" if your repo uses that branch
  schedule:
    - cron: '54 14 * * *'  # Runs daily at 08:15 UTC

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 21f3000330@ds.study.iitm.ac.in
        run: echo "Running!"

      - name: Make a change
        run: echo "$(date)" > last-run.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "21f3000330@ds.study.iitm.ac.in"

      - name: Commit and Push Changes
        run: |
          git add last-run.txt
          git commit -m "Automated commit - $(date)"
          git push
