name: Daily Commit

on:
  schedule:
    - cron: "04 15 * * *"  # Runs every day at 00:00 UTC (change as needed)

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 21f3000330@ds.study.iitm.ac.in  # Required email in name
        run: echo "Automated commit at $(date)" >> daily-log.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add daily-log.txt
          git commit -m "Daily commit - $(date)"
          git push
