name: Master

on:
  push:
    branches:
      - main  # Change if your branch is "master"
  schedule:
    - cron: '43 14 9 2 0'  # Runs daily at 08:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use latest version

      - name: Running
        run: echo "Running!"
