name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '37 14 9 2 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"
