name: Master

on:
  push:
    branches:
      - main  # Change if your branch is "master"
  schedule:
    - cron: '51 14 * * *'  # Runs daily at 08:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use latest version

      - name: 21f3000330@ds.study.iitm.ac.in
        run: echo "Running!"
